### ISSUE TITLE
Questions about the `Convergence#do` API

### ISSUE THREAD

**Issue by pittst3r** [bigtestjs/convergence#6]
In writing type declarations I noticed that the signature of the `#do` callback is:

```ts
type SideEffect<T, U> = (previous: U) => T;
```

This struck me as odd because I don't like mixing return values and side-effects, and it is my understanding that `Convergence#do` is primarily about side-effects. In its current incarnation `#do` does the following:

- Performs side-effects
- Maps the previous inner value to a new inner value if provided
- Flat maps the previous inner value to a new inner value if provided a `Convergence` or `Promise` instance

Basically, I guess I am wondering if it would make sense to restrict `#do` to side-effects only and create two new methods: `#map` and `#flatMap`, which take care of the other two bullet points respectively.

The signatures would go from this:

```ts
declare class Convergence<T> {
  // ...
  do<U>(callback: (previous: T) => U): Convergence<U>;
}
```

To this:

```ts
declare class Convergence<T> {
  // ...
  do(callback: (previous: T) => void): Convergence<T>;
  map<U>(callback: (previous: T) => U): Convergence<U>;
  flatMap<U>(callback: (previous: T) => Convergence<U> | Promise<U>): Convergence<U>;
}
```

Of note is the fact that this change would make it possible to have higher-order convergences (increasing the API surface area a bit), the implications of which I have not thought through yet and I don't know if that would be good or bad.

Just wanted to kick off this discussion and see if what I'm thinking makes sense or if I'm off base.

**Comment by wwilsman** [comment]
I think making a `#flatMap` option makes sense if we were to split out this functionality.

However, I'm unsure what `#map` would achieve?

Currently, `#when`, `#always`, and `#do` all curry an optional return value to the next function in the stack. But this completely optional, as they will work the same without return values

```js
new Convergence()
  .when(() => 100) // probably wouldn't do this, but just for conjecture...
  .do((n) => n * 5)          // receives `100` from `#when`
  .always((n) => n === 500)  // receives `500` from `#do`
  .do((b) => console.log(b)) // logs `true` from `#always`
```

```js
// instead of returning, you could also use a scoped variable
let total;

new Convergence()
  .when(() => { total = 100 })
  .do(() => { total *= 5 })
  .always(() => { expect(total).to.equal(500) })
  .do(() => { console.log(total) })
```

So if we restrict `#do` to consume the return value, that changes it's ability to work with `#when` and `#always`. If we also remove this ability from `#when` and `#always`, that would require major changes to `@bigtest/interactor` as it makes heavy use of this feature.

I can totally see an argument for `#flatMap`, however. But am wondering, when would you ever use `#do` if we had `#flatMap`?

For example:

```js
new Convergence()
  .do(() => promiseSideEffectWithValue()) // waits for the promise, does not curry
  .flatMap(() => promiseSideEffectWithValue()) // waits for the promise, curries
```

Out of the two, I'd be inclined to always use `#flatMap` since it does exactly what `#do` does anyway, but with the benefit of optionally currying the return value. Something the other methods already do as well.

After writing this out, I think it might help to think of any convergence method as having an optional map feature. `#do` is just analogous to `#flatMap` and the API sounds nice when you read `.when().do().always()` as oppose to `.when().flatMap().always()`

**Comment by wwilsman** [comment]
This does raise the point that we need to up our docs game to better explain these things

**Comment by pittst3r** [comment]
Gotcha. Thanks for walking me through that. My trouble was I was expecting `Convergence#do` to behave like RxJS's `Observable#do` or Ruby's `Object#tap`, where the inner value flows through regardless of the value the callback returns. But in the context of `.when().do().always()` vs. `.when().flatMap().always()` and the fact that all these methods work the same it makes a lot more sense to me.

> But am wondering, when would you ever use #do if we had #flatMap?

The `console` API or synchronously changing context were the two things I had in mind.

At this point the only argument I see for having two separate methods—a method that performs only side effects and passes the previous value through and a method that flat maps—is the possibility of something like this trolling people:

```js
// Existing API
new Convergence()
  .when(() => 100)
  .do((n) => n * 5)
  .do((n) => console.log(n))
  .always((n) => n === 500)
  .do((b) => console.log(b))
```

When what they actually need to do is this:

```js
// Existing API
new Convergence()
  .when(() => 100)
  .do((n) => n * 5)
  .do((n) => {
    console.log(n);
    return n;
  })
  .always((n) => n === 500)
  .do((b) => console.log(b))
```

If you like the idea of breaking into two methods, what about keeping `#do` the same but adding a method called `#tap` that only performs side effects and passes the value through? If not I'm cool to drop it. Have a better understanding now.

I think typing this library got me into hyper-analysis mode. 😅

**Comment by wwilsman** [comment]
As I was reading your example, I immediately thought `#tap` would be a good method to add that does this. Then you said it yourself!

I think your example clears it up for me and `#tap` sounds perfect for that. "Don't interrupt the convergence or wait for anything, just do something else at this time."

**Comment by pittst3r** [comment]
Great minds think alike! I can work on adding this. Probably won't get through it this week though.

**Comment by wwilsman** [comment]
With #21, tap-like behavior was just added to all functions in the queue when `undefined` is returned.

Here's what the signature would look like:

```ts
declare class Convergence<R> {
  // ...
  do(callback: (value: R) => undefined): Convergence<R>;
  do<U>(callback: (value: R) => U | PromiseLike<U> | Convergence<U>): Convergence<U>;
}
```

This applies to `when` and `always` as well!
