### ISSUE TITLE
Change "stack" terminology to "queue"

### ISSUE THREAD

**Issue by pittst3r** [bigtestjs/convergence#9]
It appears that `Convergence#_stack` is being used in a FIFO manner, but it's my understanding that a stack is FILO. This conflict is causing me to be confused. Is one of these assumptions incorrect? If not, would "queue" be more accurate?

**Comment by wwilsman** [comment]
I agree, "queue" is more accurate. You're more than welcome to make this change, otherwise I'll probably do it this Friday.  👍

**Comment by pittst3r** [comment]
Sweet. I can take care of it.

**Comment by pittst3r** [comment]
Donezo

**Comment by Robdel12** [comment]
Yassss! 🎉
